### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'username')

### ISSUE THREAD

**Issue by MarikoJanes** [learn-co-curriculum/phase-4-rails-putting-it-all-together-auth#4] opened 2022-06-14 03:00 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5181/assignments/180790?module_item_id=398957

### Concern

On the client-side, there is an undefined property on `src/pages/RecipeList.js:26`.  This undefined property causes an unhandled rejection when you load a page.

### Suggested Changes

Change `{recipe.user.username}` to `{recipe.username}` on line 26.

**Comment by lizbur10** [comment] 2022-07-01 19:29
Hi @MarikoJanes! I'm sorry to hear you  ran into a problem with this lab. I was not able to reproduce the error, so I'm going to go ahead and close this issue. 

If you are still unable to resolve the issue, I suggest you go to your instructor for help or use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

**Closed as completed by lizbur10** 2022-07-01 19:29 UTC
Labels: se curriculum
